web:
  image: nginx:latest
  ports:
    - "8088:80"
  links:
    - php
  volumes:
    - ./:/app
    - ./docker/nginx/eventsourcing-api.conf:/etc/nginx/conf.d/eventsourcing-api.conf

php:
  build: docker/php-fpm
  volumes:
    - ./:/app
  working_dir: /app